Tk-9: Completed
bruno9926/pokedex pull request #10
Opened 2022-08-17 02:39 UTC by lvgarces

2022-08-17 23:58 UTC, davidlopez9926 commented on src/PokeList/PokeList.jsx
>          <div className="pokeitem-container">
use identation

2022-08-18 00:01 UTC, bruno9926 requested changes

2022-08-18 00:01 UTC, bruno9926 commented on src/PokeList/PokeList.jsx
> +    const { pokemon, loading } = useFetchPokemon();
use the isFetching variable, another is not necessary

2022-08-18 00:31 UTC, bruno9926 approved these changes

2022-08-18 00:31 UTC, merged