TK-3: Configure SCSS
bruno9926/pokedex pull request #2
Opened 2022-07-31 01:54 UTC by DavidB208

SASS was installed in the project.
Just was modified package.json.

2022-07-31 01:59 UTC, bruno9926 commented
Otro comentario

2022-07-31 01:59 UTC, bruno9926 commented on package.json
> +    "sass": "^1.54.0",
dfafdafdasfdas

2022-07-31 02:00 UTC, DavidB208 commented on package.json
> +    "sass": "^1.54.0",
jeje

2022-07-31 02:01 UTC, bruno9926 commented
Probaste con un componente? :B

2022-07-31 02:02 UTC, bruno9926 requested changes

2022-07-31 02:02 UTC, bruno9926 commented on package.json
> +    "sass": "^1.54.0",
probar con un componente

2022-08-02 02:04 UTC, bruno9926 approved these changes

2022-08-02 02:05 UTC, merged