Tk 1
bruno9926/pokedex pull request #5
Opened 2022-08-04 03:14 UTC by lvgarces

2022-08-05 02:34 UTC, davidlopez9926 reviewed
fix

2022-08-05 02:34 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.jsx
> +import React, { useState } from "react";
delete useState, you are not using it

2022-08-05 02:38 UTC, davidlopez9926 reviewed
aaaa

2022-08-05 02:38 UTC, davidlopez9926 requested changes
:(

2022-08-05 02:40 UTC, davidlopez9926 commented on src/Pokeitem/components/InfoPokemon.jsx
> +            <p className="info-poke">{name}</p>
what if I put a large name? it should be cropped

2022-08-05 02:41 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.jsx
> +import img1 from "./MiniPokemon.png";
use more descriptive names for these images

2022-08-05 02:42 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.jsx
> +    <label>
why a label and not a div?

2022-08-05 02:43 UTC, davidlopez9926 commented on src/Pokeitem/components/InfoPokemon.jsx
> +import React from "react";
Put this component in a InfoPokemon folder, with its own stylesheet

2022-08-05 02:44 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.scss
> +	&:checked {
you could simplfy this selector using
&:checked + .container-pokeitem instead

2022-08-05 02:45 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.scss
> +				border: #FF6F6F;
this could be a variable, since you are using this color twice

2022-08-05 02:45 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.scss
> +				stroke: rgb(0, 92, 173);
delete

2022-08-05 02:45 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.scss
> +				stroke-width: 5rem;
delete

2022-08-05 02:46 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.scss
> +.info-content{
Put InfoPokemon styles in its own stylesheet

2022-08-05 02:46 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.scss
> +.margin-img{
this could be a mixin, used in both previous classes

2022-08-05 02:46 UTC, davidlopez9926 commented on src/Pokeitem/Pokeitem.scss
> +    justify-content: start;
use start-flex instead

2022-08-09 01:59 UTC, bruno9926 requested changes

2022-08-09 01:59 UTC, bruno9926 commented on src/App.js
> +      <Pokeitem></Pokeitem>
component receives all data as props

2022-08-09 02:17 UTC, bruno9926 approved these changes

2022-08-09 02:18 UTC, merged